source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'

gem 'slim-rails'
gem 'sass-rails', '~> 5.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier', '>= 1.3.0'
gem 'pry-rails'
gem 'gon'

#group :views
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'backbone-on-rails'
#end

gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring', '1.3.4'
end

