# OBJ = lab2spo.o 
# CFLAGS = -Wall -std=c99

# all: main

# main: $(OBJ)
# 	g++ $(CFLAGS) $(OBJ) -o main -lncurses

# %.o : %.c
# 	g++ $(CFLAGS) -c $<

# clean:
# 	rm main $(OBJ)
g++ main.cpp -o main.o -lncurses